name: gradient-flow-sdes
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10,<3.13
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pip
  - pip:
      - absl-py
      - chex
      - click
      - equinox
      - etils
      - flax
      - fsspec
      - gitpython
      - jax
      - jaxlib
      - jaxopt
      - jaxtyping
      - lineax
      - ml-dtypes
      - networkx
      - opt-einsum
      - optax
      - orbax-checkpoint
      - ott-jax
      - pillow
      - pot
      - protobuf
      - pybtex
      - pybtex-docutils
      - pyyaml
      - requests
      - rich
      - scipy
      - sentry-sdk
      - sphinx
      - sphinx-rtd-theme
      - sympy
      - tensorstore
      - torch
      - wandb
